# This is a basic workflow to help you get started with Actions

name: TableAugmentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - "test"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "updateTables"
  updateTestTables:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
        with:
          python-version: 3.9 #install the python version needed
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          
      - name: Get changed files
        uses: tj-actions/changed-files@v31
      - name: Check for .sql files 
        run: |
          ls -l | grep ${{ steps.changed-files.outputs.all_changed_files }};
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "details for: $file"
            cat $file
          done;
      
  
          
      - name: install dbsqlcli
        run: |
          python3 -m pip install dbsqlcli
          
      - name: initial setup of dbsqlcli
        run: |
          dbsqlcli
          
      - name: connect to Databricks-sql-cli
        if: always()  # because previous step always turn out an error 
        run: |          
          
          dbsqlcli -e "SELECT * FROM default.diamonds LIMIT 2" --hostname ${{ secrets.DBSQLCLI_HOST_NAME }} --http-path ${{ secrets.DBSQLCLI_HTTP_PATH }} --access-token ${{ secrets.DBSQLCLI_ACCESS_TOKEN }}
          
          
          
          # todo: check if tables exists within the cluster. -> perform short simple query. 
          # todo: check if commit file name starts with "create", ends with ".sql"
          
      - name: print log file
        if: always()
        run: cat ~/.dbsqlcli/app.log
